// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: hello/v1/hello.proto

package hellov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_hello_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_hello_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayHelloResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SayManyHellosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayManyHellosRequest) Reset() {
	*x = SayManyHellosRequest{}
	mi := &file_hello_v1_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayManyHellosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayManyHellosRequest) ProtoMessage() {}

func (x *SayManyHellosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayManyHellosRequest.ProtoReflect.Descriptor instead.
func (*SayManyHellosRequest) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{2}
}

func (x *SayManyHellosRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayManyHellosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayManyHellosResponse) Reset() {
	*x = SayManyHellosResponse{}
	mi := &file_hello_v1_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayManyHellosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayManyHellosResponse) ProtoMessage() {}

func (x *SayManyHellosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayManyHellosResponse.ProtoReflect.Descriptor instead.
func (*SayManyHellosResponse) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *SayManyHellosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayManyHellosResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SayHelloToEveryoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloToEveryoneRequest) Reset() {
	*x = SayHelloToEveryoneRequest{}
	mi := &file_hello_v1_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloToEveryoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloToEveryoneRequest) ProtoMessage() {}

func (x *SayHelloToEveryoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloToEveryoneRequest.ProtoReflect.Descriptor instead.
func (*SayHelloToEveryoneRequest) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{4}
}

func (x *SayHelloToEveryoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloToEveryoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloToEveryoneResponse) Reset() {
	*x = SayHelloToEveryoneResponse{}
	mi := &file_hello_v1_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloToEveryoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloToEveryoneResponse) ProtoMessage() {}

func (x *SayHelloToEveryoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloToEveryoneResponse.ProtoReflect.Descriptor instead.
func (*SayHelloToEveryoneResponse) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{5}
}

func (x *SayHelloToEveryoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayHelloToEveryoneResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SayHelloContinuousRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloContinuousRequest) Reset() {
	*x = SayHelloContinuousRequest{}
	mi := &file_hello_v1_hello_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloContinuousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloContinuousRequest) ProtoMessage() {}

func (x *SayHelloContinuousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloContinuousRequest.ProtoReflect.Descriptor instead.
func (*SayHelloContinuousRequest) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{6}
}

func (x *SayHelloContinuousRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloContinuousResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloContinuousResponse) Reset() {
	*x = SayHelloContinuousResponse{}
	mi := &file_hello_v1_hello_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloContinuousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloContinuousResponse) ProtoMessage() {}

func (x *SayHelloContinuousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_v1_hello_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloContinuousResponse.ProtoReflect.Descriptor instead.
func (*SayHelloContinuousResponse) Descriptor() ([]byte, []int) {
	return file_hello_v1_hello_proto_rawDescGZIP(), []int{7}
}

func (x *SayHelloContinuousResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayHelloContinuousResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_hello_v1_hello_proto protoreflect.FileDescriptor

const file_hello_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x14hello/v1/hello.proto\x12\bhello.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x0fSayHelloRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\"g\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x14SayManyHellosRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\"l\n" +
	"\x15SayManyHellosResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\":\n" +
	"\x19SayHelloToEveryoneRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\"q\n" +
	"\x1aSayHelloToEveryoneResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\":\n" +
	"\x19SayHelloContinuousRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\"q\n" +
	"\x1aSayHelloContinuousResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBs\n" +
	"\fcom.hello.v1B\n" +
	"HelloProtoP\x01Z\x16protogen/hello;hellov1\xa2\x02\x03HXX\xaa\x02\bHello.V1\xca\x02\bHello\\V1\xe2\x02\x14Hello\\V1\\GPBMetadata\xea\x02\tHello::V1b\x06proto3"

var (
	file_hello_v1_hello_proto_rawDescOnce sync.Once
	file_hello_v1_hello_proto_rawDescData []byte
)

func file_hello_v1_hello_proto_rawDescGZIP() []byte {
	file_hello_v1_hello_proto_rawDescOnce.Do(func() {
		file_hello_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_v1_hello_proto_rawDesc), len(file_hello_v1_hello_proto_rawDesc)))
	})
	return file_hello_v1_hello_proto_rawDescData
}

var file_hello_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hello_v1_hello_proto_goTypes = []any{
	(*SayHelloRequest)(nil),            // 0: hello.v1.SayHelloRequest
	(*SayHelloResponse)(nil),           // 1: hello.v1.SayHelloResponse
	(*SayManyHellosRequest)(nil),       // 2: hello.v1.SayManyHellosRequest
	(*SayManyHellosResponse)(nil),      // 3: hello.v1.SayManyHellosResponse
	(*SayHelloToEveryoneRequest)(nil),  // 4: hello.v1.SayHelloToEveryoneRequest
	(*SayHelloToEveryoneResponse)(nil), // 5: hello.v1.SayHelloToEveryoneResponse
	(*SayHelloContinuousRequest)(nil),  // 6: hello.v1.SayHelloContinuousRequest
	(*SayHelloContinuousResponse)(nil), // 7: hello.v1.SayHelloContinuousResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_hello_v1_hello_proto_depIdxs = []int32{
	8, // 0: hello.v1.SayHelloResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: hello.v1.SayManyHellosResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: hello.v1.SayHelloToEveryoneResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: hello.v1.SayHelloContinuousResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hello_v1_hello_proto_init() }
func file_hello_v1_hello_proto_init() {
	if File_hello_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_v1_hello_proto_rawDesc), len(file_hello_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_v1_hello_proto_goTypes,
		DependencyIndexes: file_hello_v1_hello_proto_depIdxs,
		MessageInfos:      file_hello_v1_hello_proto_msgTypes,
	}.Build()
	File_hello_v1_hello_proto = out.File
	file_hello_v1_hello_proto_goTypes = nil
	file_hello_v1_hello_proto_depIdxs = nil
}
