// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: hello/v1/service.proto

package hellov1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hello_v1_service_proto protoreflect.FileDescriptor

const file_hello_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16hello/v1/service.proto\x12\bhello.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14hello/v1/hello.proto2\x8c\x04\n" +
	"\fHelloService\x12a\n" +
	"\bSayHello\x12\x19.hello.v1.SayHelloRequest\x1a\x1a.hello.v1.SayHelloResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/hello/v1/say-hello\x12x\n" +
	"\rSayManyHellos\x12\x1e.hello.v1.SayManyHellosRequest\x1a\x1f.hello.v1.SayManyHellosResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/hello/v1/say-many-hellos0\x01\x12\x8d\x01\n" +
	"\x12SayHelloToEveryone\x12#.hello.v1.SayHelloToEveryoneRequest\x1a$.hello.v1.SayHelloToEveryoneResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/hello/v1/say-hello-to-everyone(\x01\x12\x8e\x01\n" +
	"\x12SayHelloContinuous\x12#.hello.v1.SayHelloContinuousRequest\x1a$.hello.v1.SayHelloContinuousResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/hello/v1/say-hello-continuous(\x010\x01Bu\n" +
	"\fcom.hello.v1B\fServiceProtoP\x01Z\x16protogen/hello;hellov1\xa2\x02\x03HXX\xaa\x02\bHello.V1\xca\x02\bHello\\V1\xe2\x02\x14Hello\\V1\\GPBMetadata\xea\x02\tHello::V1b\x06proto3"

var file_hello_v1_service_proto_goTypes = []any{
	(*SayHelloRequest)(nil),            // 0: hello.v1.SayHelloRequest
	(*SayManyHellosRequest)(nil),       // 1: hello.v1.SayManyHellosRequest
	(*SayHelloToEveryoneRequest)(nil),  // 2: hello.v1.SayHelloToEveryoneRequest
	(*SayHelloContinuousRequest)(nil),  // 3: hello.v1.SayHelloContinuousRequest
	(*SayHelloResponse)(nil),           // 4: hello.v1.SayHelloResponse
	(*SayManyHellosResponse)(nil),      // 5: hello.v1.SayManyHellosResponse
	(*SayHelloToEveryoneResponse)(nil), // 6: hello.v1.SayHelloToEveryoneResponse
	(*SayHelloContinuousResponse)(nil), // 7: hello.v1.SayHelloContinuousResponse
}
var file_hello_v1_service_proto_depIdxs = []int32{
	0, // 0: hello.v1.HelloService.SayHello:input_type -> hello.v1.SayHelloRequest
	1, // 1: hello.v1.HelloService.SayManyHellos:input_type -> hello.v1.SayManyHellosRequest
	2, // 2: hello.v1.HelloService.SayHelloToEveryone:input_type -> hello.v1.SayHelloToEveryoneRequest
	3, // 3: hello.v1.HelloService.SayHelloContinuous:input_type -> hello.v1.SayHelloContinuousRequest
	4, // 4: hello.v1.HelloService.SayHello:output_type -> hello.v1.SayHelloResponse
	5, // 5: hello.v1.HelloService.SayManyHellos:output_type -> hello.v1.SayManyHellosResponse
	6, // 6: hello.v1.HelloService.SayHelloToEveryone:output_type -> hello.v1.SayHelloToEveryoneResponse
	7, // 7: hello.v1.HelloService.SayHelloContinuous:output_type -> hello.v1.SayHelloContinuousResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_v1_service_proto_init() }
func file_hello_v1_service_proto_init() {
	if File_hello_v1_service_proto != nil {
		return
	}
	file_hello_v1_hello_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_v1_service_proto_rawDesc), len(file_hello_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_v1_service_proto_goTypes,
		DependencyIndexes: file_hello_v1_service_proto_depIdxs,
	}.Build()
	File_hello_v1_service_proto = out.File
	file_hello_v1_service_proto_goTypes = nil
	file_hello_v1_service_proto_depIdxs = nil
}
