// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: resiliency/v1/service.proto

package resiliencyv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_resiliency_v1_service_proto protoreflect.FileDescriptor

const file_resiliency_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bresiliency/v1/service.proto\x12\rresiliency.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1eresiliency/v1/resiliency.proto2\xc3\x04\n" +
	"\x11ResiliencyService\x12\x82\x01\n" +
	"\x0fUnaryResiliency\x12 .resiliency.v1.ResiliencyRequest\x1a!.resiliency.v1.ResiliencyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/resiliency/v1/unary-resiliency\x12\x86\x01\n" +
	"\x10ServerResiliency\x12 .resiliency.v1.ResiliencyRequest\x1a!.resiliency.v1.ResiliencyResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /resiliency/v1/server-resiliency0\x01\x12\x86\x01\n" +
	"\x10ClientResiliency\x12 .resiliency.v1.ResiliencyRequest\x1a!.resiliency.v1.ResiliencyResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /resiliency/v1/client-resiliency(\x01\x12\x96\x01\n" +
	"\x17BidirectionalResiliency\x12 .resiliency.v1.ResiliencyRequest\x1a!.resiliency.v1.ResiliencyResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/resiliency/v1/bidirectional-resiliency(\x010\x01B\x98\x01\n" +
	"\x11com.resiliency.v1B\fServiceProtoP\x01Z protogen/resiliency;resiliencyv1\xa2\x02\x03RXX\xaa\x02\rResiliency.V1\xca\x02\rResiliency\\V1\xe2\x02\x19Resiliency\\V1\\GPBMetadata\xea\x02\x0eResiliency::V1b\x06proto3"

var file_resiliency_v1_service_proto_goTypes = []any{
	(*ResiliencyRequest)(nil),  // 0: resiliency.v1.ResiliencyRequest
	(*ResiliencyResponse)(nil), // 1: resiliency.v1.ResiliencyResponse
}
var file_resiliency_v1_service_proto_depIdxs = []int32{
	0, // 0: resiliency.v1.ResiliencyService.UnaryResiliency:input_type -> resiliency.v1.ResiliencyRequest
	0, // 1: resiliency.v1.ResiliencyService.ServerResiliency:input_type -> resiliency.v1.ResiliencyRequest
	0, // 2: resiliency.v1.ResiliencyService.ClientResiliency:input_type -> resiliency.v1.ResiliencyRequest
	0, // 3: resiliency.v1.ResiliencyService.BidirectionalResiliency:input_type -> resiliency.v1.ResiliencyRequest
	1, // 4: resiliency.v1.ResiliencyService.UnaryResiliency:output_type -> resiliency.v1.ResiliencyResponse
	1, // 5: resiliency.v1.ResiliencyService.ServerResiliency:output_type -> resiliency.v1.ResiliencyResponse
	1, // 6: resiliency.v1.ResiliencyService.ClientResiliency:output_type -> resiliency.v1.ResiliencyResponse
	1, // 7: resiliency.v1.ResiliencyService.BidirectionalResiliency:output_type -> resiliency.v1.ResiliencyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resiliency_v1_service_proto_init() }
func file_resiliency_v1_service_proto_init() {
	if File_resiliency_v1_service_proto != nil {
		return
	}
	file_resiliency_v1_resiliency_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resiliency_v1_service_proto_rawDesc), len(file_resiliency_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resiliency_v1_service_proto_goTypes,
		DependencyIndexes: file_resiliency_v1_service_proto_depIdxs,
	}.Build()
	File_resiliency_v1_service_proto = out.File
	file_resiliency_v1_service_proto_goTypes = nil
	file_resiliency_v1_service_proto_depIdxs = nil
}
